# QUESTION 1

In [4]:
import numpy as np
import matplotlib.pyplot as plt
nx=5
ny=4
a=np.ones((nx,ny))
for i in range(nx):
  for j in range(ny):
    a[i,j]=np.random.randint(1,50)
print(a)
b=[]
for i in range(nx):
  b.append(np.max(a[i,:]))
print(b)
mean=np.sum(a)/20
d=[]
for i in range(nx):
  for j in range(ny):
    if(a[i,j]<=mean):
      d.append(a[i,j])

print(np.array(d))
print(mean)
def numpy_boundary_traversal(matrix):
  clock=[]
  nf,ng=matrix.shape
  for i in range(1):
    for j in range(ng):
      clock.append(matrix[0,j])
  for j in range(1):
    for i in range(nf-1):
      clock.append(matrix[i+1,ng-1])
  for i in range(1):
    for j in range(ng-1):
      clock.append(matrix[nf-1,ng-2-j])
  for j in range(1):
    for i in range(nf-2):
      clock.append(matrix[nf-2-i,0])
  return np.array(clock)
numpy_boundary_traversal(a)







[[30. 11. 43. 43.]
 [33. 45. 29. 36.]
 [ 5. 37. 25. 12.]
 [37. 39. 24. 17.]
 [15. 32. 48. 16.]]
[np.float64(43.0), np.float64(45.0), np.float64(37.0), np.float64(39.0), np.float64(48.0)]
[11.  5. 25. 12. 24. 17. 15. 16.]
28.85


array([30., 11., 43., 43., 36., 12., 17., 16., 48., 32., 15., 37.,  5.,
       33.])

# QUESTION 2

In [40]:
one_d=np.ones(20)

for i in range(20):
  one_d[i]=np.random.uniform(0,10)

print(one_d.round(2))
print(one_d.max().round(2))
print(one_d.min().round(2))
print(np.median(one_d.round(2)))

for i in range(20):
  if(one_d[i]<5):
    one_d[i]=(one_d[i])*(one_d[i])
print(one_d.round(2))

def numpy_alternate_sort(arr):
  a=arr.copy()
  x=arr.shape[0]
  for _ in range(20):
    for i in range(x-1):
      if(a[i+1]<a[i]):
        temp=a[i]
        a[i]=a[i+1]
        a[i+1]=temp
  print(a)
  p=[]

  for i in range(int (x/2)):
    c=i
    d=-i-1
    p.append(a[c])
    p.append(a[d])
  if x%2==1:
    p.append(a[int(x/2)])

  print(np.array(p))

numpy_alternate_sort(one_d)



[3.24 6.57 7.18 4.12 7.65 6.75 6.   4.35 0.96 1.55 0.83 7.7  5.1  6.82
 7.59 0.7  6.3  4.01 3.54 8.51]
8.51
0.7
5.55
[10.48  6.57  7.18 16.99  7.65  6.75  6.   18.93  0.92  2.39  0.68  7.7
  5.1   6.82  7.59  0.48  6.3  16.12 12.56  8.51]
[ 0.48347526  0.68066669  0.91938827  2.39202719  5.10178722  5.99624716
  6.29541775  6.57206996  6.74903696  6.8161663   7.1819037   7.58529013
  7.64609422  7.69623505  8.50668058 10.47794951 12.55691787 16.11982481
 16.98593307 18.92678668]
[ 0.48347526 18.92678668  0.68066669 16.98593307  0.91938827 16.11982481
  2.39202719 12.55691787  5.10178722 10.47794951  5.99624716  8.50668058
  6.29541775  7.69623505  6.57206996  7.64609422  6.74903696  7.58529013
  6.8161663   7.1819037 ]


# QUESTION 3

In [81]:
import pandas as pd
data={
    'Name':['Ayush','Ayush', 'Ayush','Om','Om','Om','Om','Aum','Aum','Aum'],
    'Subject':['Math',
        'English',
        'Physics',
        'Chemistry',
        'English',
        'Physics',
        'Chemistry',
        'English ',
        'Physics',
        'Chemistry'],
    'Score':[np.random.randint(50,100) for i in range(10)],
    'Grade':[None for i in range(10)]
}
df=pd.DataFrame(data)
df['Grade']
def grade_allocation(Score):
  if Score>=90:
    return 'A'
  elif Score>=80:
    return 'B'
  elif Score>=70:
    return 'C'
  elif Score>=60:
    return 'D'
  else:
    return 'F'
df['Grade']=df['Score'].apply(grade_allocation)

sorted_df=df.sort_values(by='Score', ascending=False)
print(sorted_df)
average_scores=df.groupby('Subject')['Score'].mean()
print(average_scores)
def pandas_filter_pass(dataframe):
  return dataframe[dataframe['Grade'].isin(['A','B'])]
print(pandas_filter_pass(df))





    Name    Subject  Score Grade
1  Ayush    English     88     B
0  Ayush       Math     86     B
8    Aum    Physics     78     C
3     Om  Chemistry     62     D
4     Om    English     56     F
5     Om    Physics     55     F
9    Aum  Chemistry     55     F
2  Ayush    Physics     54     F
6     Om  Chemistry     52     F
7    Aum   English      51     F
Subject
Chemistry    56.333333
English      72.000000
English      51.000000
Math         86.000000
Physics      62.333333
Name: Score, dtype: float64
    Name  Subject  Score Grade
0  Ayush     Math     86     B
1  Ayush  English     88     B


# Question 4

In [84]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# 1. Create synthetic dataset
positive_reviews = ["I loved this movie!", "Fantastic film!", "Best movie ever!", "Brilliant acting!", "Great direction!"] * 10
negative_reviews = ["I hated this movie.", "Terrible film!", "Worst movie ever.", "Awful acting!", "Poor direction."] * 10

reviews = positive_reviews + negative_reviews
sentiments = ['positive'] * 50 + ['negative'] * 50

df = pd.DataFrame({'Review': reviews, 'Sentiment': sentiments})

# 2. Tokenize using CountVectorizer
vectorizer = CountVectorizer(max_features=500, stop_words='english')
X = vectorizer.fit_transform(df['Review'])
y = df['Sentiment']

# 3. Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Train Multinomial Naive Bayes
model = MultinomialNB()
model.fit(X_train, y_train)

# 5. Evaluate the model
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy on test set:", accuracy)

# 6. Predict function
def predict_review_sentiment(model, vectorizer, review):
    review_vector = vectorizer.transform([review])
    prediction = model.predict(review_vector)
    return prediction[0]

# Example prediction
example_review = "An absolutely amazing movie!"
print("Predicted sentiment:", predict_review_sentiment(model, vectorizer, example_review))


Accuracy on test set: 1.0
Predicted sentiment: negative


# Question 5

In [85]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score
good_feedback = [
    "Great product!", "Excellent quality", "Very satisfied", "Highly recommend", "Amazing value"
] * 10

bad_feedback = [
    "Terrible experience", "Poor quality", "Not satisfied", "Would not recommend", "Waste of money"
] * 10

texts = good_feedback + bad_feedback
labels = ['good'] * 50 + ['bad'] * 50

df = pd.DataFrame({'Text': texts, 'Label': labels})


vectorizer = TfidfVectorizer(max_features=300, stop_words='english', lowercase=True)
X = vectorizer.fit_transform(df['Text'])
y = df['Label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

precision = precision_score(y_test, y_pred, pos_label='good')
recall = recall_score(y_test, y_pred, pos_label='good')
f1 = f1_score(y_test, y_pred, pos_label='good')

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


def text_preprocess_vectorize(texts, vectorizer):
    """
    Takes a list of text samples and a fitted TfidfVectorizer,
    returns the TF-IDF feature matrix.
    """
    return vectorizer.transform(texts)

# Example usage
new_texts = ["Fantastic purchase", "Really bad product"]
X_new = text_preprocess_vectorize(new_texts, vectorizer)
predictions = model.predict(X_new)
print("Predicted labels:", predictions)


Precision: 1.0
Recall: 0.7857142857142857
F1 Score: 0.88
Predicted labels: ['bad' 'good']
